"""Rendering a SearchResult as the .txt file the user asked for.

Plain text on purpose: it opens in Notepad, greps cleanly, pastes into a case
file, and will still be readable in ten years. Lines are wrapped to 96 columns
so it stays legible in a fixed-width viewer without horizontal scrolling.
"""

from __future__ import annotations

import textwrap
import time
from pathlib import Path
from typing import List, Optional

from .. import APP_NAME, __version__
from .models import (
    CONFIDENCE_LABEL,
    CONFIRMED,
    ERROR,
    LIKELY,
    PIVOT,
    POSSIBLE,
    SearchResult,
)
from .naming import report_filename, unique_path
from .query import TYPE_LABELS

WIDTH = 96
INDENT = "    "

DISCLAIMER = (
    "This report lists information published openly on the public internet, "
    "gathered by checking whether public profile URLs resolve and by reading "
    "publicly served page metadata. Automated checks produce false positives: "
    "a handle matching on a site does not prove the same person owns it. "
    "Verify anything you intend to rely on, and use this only for purposes you "
    "are lawfully entitled to."
)


def _rule(char: str = "=") -> str:
    return char * WIDTH


def _heading(text: str) -> List[str]:
    return [_rule("="), text.upper(), _rule("=")]


def _wrap(text: str, indent: str = INDENT) -> List[str]:
    if not text:
        return []
    return textwrap.wrap(
        text,
        width=WIDTH,
        initial_indent=indent,
        subsequent_indent=indent,
        break_long_words=False,
        break_on_hyphens=False,
    ) or [indent + text]


def _timestamp(value: float) -> str:
    if not value:
        return "unknown"
    return time.strftime("%Y-%m-%d %H:%M:%S %Z", time.localtime(value))


def render(result: SearchResult) -> str:
    """Build the full text of the report."""
    lines: List[str] = []

    lines += _heading(f"{APP_NAME} - search report")
    lines.append("")
    lines.append(f"  Query          : {result.query}")
    lines.append(f"  Detected as    : {TYPE_LABELS.get(result.query_type, result.query_type)}")
    lines.append(f"  Started        : {_timestamp(result.started_at)}")
    lines.append(f"  Finished       : {_timestamp(result.finished_at)}")
    lines.append(f"  Duration       : {result.duration:.1f} seconds")
    lines.append(f"  Findings       : {result.total_findings} "
                 f"({result.hit_count} confirmed or likely accounts/records)")
    if result.cancelled:
        lines.append("  Status         : STOPPED BY USER - this report is incomplete")
    lines.append(f"  Generated by   : {APP_NAME} v{__version__}")
    lines.append("")

    # Summary counts per section, so the reader knows what to expect.
    lines.append(_rule("-"))
    lines.append("  CONTENTS")
    for index, section in enumerate(result.sections, start=1):
        lines.append(f"    {index}. {section.name} ({len(section.findings)} item(s))")
    lines.append(_rule("-"))
    lines.append("")

    for index, section in enumerate(result.sections, start=1):
        lines += _heading(f"{index}. {section.name}")
        lines.append("")

        if not section.findings:
            lines.append(f"{INDENT}(nothing found)")
            lines.append("")

        for finding in section.sorted_findings():
            marker = {
                CONFIRMED: "[+]", LIKELY: "[~]", POSSIBLE: "[?]",
                PIVOT: "[>]", ERROR: "[!]",
            }.get(finding.confidence, "[i]")

            lines.append(f"  {marker} {finding.title}")
            if finding.url:
                lines.append(f"{INDENT}URL        : {finding.url}")
            label = CONFIDENCE_LABEL.get(finding.confidence, finding.confidence)
            status = f" (HTTP {finding.status})" if finding.status else ""
            lines.append(f"{INDENT}Confidence : {label}{status}")
            if finding.detail:
                lines.append(f"{INDENT}Detail     :")
                lines += _wrap(finding.detail, INDENT + "  ")
            # Column width adapts to the longest key in this finding, so
            # "E.164" and "Carrier (at assignment)" still line up with each other.
            attributes = {k: v for k, v in finding.attributes.items() if v}
            if attributes:
                key_width = max(11, max(len(k) for k in attributes))
                continuation = INDENT + " " * (key_width + 2)
                for key, value in attributes.items():
                    first = f"{INDENT}{key:<{key_width}}: "
                    wrapped = textwrap.wrap(
                        str(value), width=WIDTH,
                        initial_indent=first,
                        subsequent_indent=continuation,
                        break_long_words=False, break_on_hyphens=False,
                    )
                    lines += wrapped or [first + str(value)]
            lines.append("")

        for note in section.notes:
            lines.append(f"{INDENT}Note:")
            lines += _wrap(note, INDENT + "  ")
            lines.append("")

    if result.errors:
        lines += _heading("Errors")
        lines.append("")
        for error in result.errors:
            lines += _wrap(error, INDENT)
        lines.append("")

    lines += _heading("Legend")
    lines.append("")
    for marker, meaning in (
        ("[+]", "Confirmed - verified by reading the page, not just the status code"),
        ("[~]", "Likely - the site answered positively but could not be verified"),
        ("[?]", "Possible - derived from the query; confirm the identity yourself"),
        ("[i]", "Information about the query itself"),
        ("[>]", "Manual follow-up - open the link and continue by hand"),
        ("[!]", "The check could not be completed"),
    ):
        lines.append(f"{INDENT}{marker}  {meaning}")
    lines.append("")

    lines += _heading("Disclaimer")
    lines.append("")
    lines += _wrap(DISCLAIMER, INDENT)
    lines.append("")
    lines.append(_rule("="))
    lines.append(f"  End of report - {APP_NAME} v{__version__}")
    lines.append(_rule("="))

    return "\n".join(lines) + "\n"


def save(result: SearchResult, directory: Path, filename: Optional[str] = None) -> Path:
    """Write the report and return the path actually used.

    ``newline=""`` plus explicit \\r\\n keeps the file readable in Notepad on
    Windows while producing identical bytes on every platform, so a report
    written on one machine looks the same on another.
    """
    directory = Path(directory).expanduser()
    directory.mkdir(parents=True, exist_ok=True)

    name = filename or report_filename(result.query, result.query_type, result.started_at)
    target = unique_path(directory, name)

    text = render(result).replace("\r\n", "\n").replace("\n", "\r\n")
    with open(target, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    return target
